### ISSUE TITLE
they cant be compile pass!

### ISSUE THREAD

**Issue by RubyKiss** [dysphie/nmrih-inventory-ornaments#1]
//// nmrih-inventory-ornaments.sp
//
// C:\steamcmd\nmrih_ds\nmrih\addons\sourcemod\scripting\nmrih-inventory-ornamen
ts.sp(91) : error 092: number of arguments does not match definition
// C:\steamcmd\nmrih_ds\nmrih\addons\sourcemod\scripting\nmrih-inventory-ornamen
ts.sp(315) : warning 228: length of initializer exceeds size of the enum field
// C:\steamcmd\nmrih_ds\nmrih\addons\sourcemod\scripting\nmrih-inventory-ornamen
ts.sp(315) : warning 228: length of initializer exceeds size of the enum field
// C:\steamcmd\nmrih_ds\nmrih\addons\sourcemod\scripting\nmrih-inventory-ornamen
ts.sp(334) : warning 228: length of initializer exceeds size of the enum field
// C:\steamcmd\nmrih_ds\nmrih\addons\sourcemod\scripting\nmrih-inventory-ornamen
ts.sp(334) : warning 228: length of initializer exceeds size of the enum field
// C:\steamcmd\nmrih_ds\nmrih\addons\sourcemod\scripting\nmrih-inventory-ornamen
ts.sp(370) : warning 228: length of initializer exceeds size of the enum field
// C:\steamcmd\nmrih_ds\nmrih\addons\sourcemod\scripting\nmrih-inventory-ornamen
ts.sp(370) : warning 228: length of initializer exceeds size of the enum field
//
// 1 Error.
//
// Compilation Time: 0.42 sec
// ----------------------------------------

**Comment by dysphie** [comment]
spcomp 1.11 is required to compile, you can also find compiled binaries in [releases](https://github.com/dysphie/nmrih-inventory-ornaments/releases/tag/beta-0.1.2)
