### ISSUE TITLE
Welder and extinguisher should glow when needed for objectives

### ISSUE THREAD

**Issue by Lunreth** [dysphie/nmrih-inventory-ornaments#2]
These 2 ornaments lose their outline once you grab them, it would be nice if they still have them, to help newbies

**Comment by Lunreth** [comment]
Maybe add particles or any effect in particular when objective requires it

**Comment by dysphie** [comment]
Implemented in 0d847a3dd1ff6ec192376e8ec6467e1ead63acf7 (0.1.3)
